#!/bin/bash
# End-to-end checks against a built tree.
#
#   tests/run_tests.sh [build-dir]
#
# Defaults to ./build. Uses the fixtures generated by make_fixtures.py plus a
# binary compiled here for the host, so all three loaders get exercised.
set -u

here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/.." && pwd)
build=${1:-$root/build}
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

astral="$build/astral"
export ASTRAL_SPECS="$build/specs"

passed=0
failed=0

check() {
    local name=$1 expected=$2 actual=$3
    if [[ "$actual" == *"$expected"* ]]; then
        printf 'ok   %s\n' "$name"
        passed=$((passed + 1))
    else
        printf 'FAIL %s\n     expected to contain: %s\n     got: %s\n' "$name" "$expected" \
            "$(printf '%s' "$actual" | head -20)"
        failed=$((failed + 1))
    fi
}

if [[ ! -x "$astral" ]]; then
    echo "no astral at $astral; build first" >&2
    exit 1
fi
if [[ ! -d "$ASTRAL_SPECS" ]]; then
    echo "no compiled specs at $ASTRAL_SPECS; build first" >&2
    exit 1
fi

python3 "$here/make_fixtures.py" "$work" >/dev/null

# ---------------------------------------------------------------- ELF (x86-64)
elf="$work/tiny_x64.elf"
check "elf: format"      "format     ELF"              "$("$astral" info "$elf")"
check "elf: language"    "x86:LE:64:default"           "$("$astral" info "$elf")"
check "elf: image base"  "image base 0x400000"         "$("$astral" info "$elf")"
check "elf: symbols"     "add_values"                  "$("$astral" info "$elf")"
check "elf: decompiles"  "return param_1"              "$("$astral" decompile -f add_values "$elf")"
check "elf: branch"      "if (100 < param_1)"          "$("$astral" decompile -f add_values "$elf")"

# --------------------------------------------------------------- PE (x86-64)
pe="$work/tiny_x64.exe"
check "pe: format"       "format     PE"               "$("$astral" info "$pe")"
check "pe: compiler"     "compiler   windows"          "$("$astral" info "$pe")"
check "pe: image base"   "image base 0x140000000"      "$("$astral" info "$pe")"
check "pe: coff symbols" "add_values"                  "$("$astral" info "$pe")"
check "pe: decompiles"   "100 <"                       "$("$astral" decompile -f add_values "$pe")"

# --------------------------------------------------------- Mach-O (host build)
cat > "$work/host.c" <<'EOF'
int add_values(int a, int b) { int s = a + b; if (s > 100) s -= 100; return s; }
int sum_array(const int *v, int n) { int t = 0; for (int i = 0; i < n; ++i) t += v[i]; return t; }
int main(void) { int v[3] = {1, 2, 3}; return add_values(sum_array(v, 3), 7); }
EOF
if cc -O1 -o "$work/host" "$work/host.c" 2>/dev/null; then
    check "macho: format"     "format     Mach-O"       "$("$astral" info "$work/host")"
    check "macho: symbols"    "sum_array"               "$("$astral" info "$work/host")"
    check "macho: loop"       "while"                   "$("$astral" decompile -f sum_array "$work/host")"
    check "macho: entry"      "entry      0x"           "$("$astral" info "$work/host")"
else
    echo "skip macho tests: no host compiler"
fi

# ------------------------------------------------------------------- raw mode
check "raw: needs language" "needs --language too" \
    "$("$astral" decompile --raw 0x1000 "$elf" 2>&1 || true)"
# The fixture's code sits at file offset 0x80, so a flat load at 0 puts it there.
check "raw: disassembles" "LEA EAX" \
    "$("$astral" disassemble --raw 0 --language 'x86:LE:64:default' -a 0x80 -d 2 "$elf")"

check "raw: p-code" "COPY" \
    "$("$astral" disassemble --raw 0 --language 'x86:LE:64:default' -a 0x80 -p 2 "$elf")"

# ------------------------------------------------- imports, strings, headers
#
# A call into another image should read as its own name, its string arguments
# should read as strings, and the stub itself is not this program's code.

cat > "$work/greet.c" <<'GREET'
#include <stdio.h>
#include <string.h>

int greet(const char *who) { return (int)strlen(who); }
/* puts, not printf: the decompiler does not recover variadic arguments, so a
   format with conversions could not be rebuilt faithfully. */
int main(void) { puts("Hello, World!"); return greet("abc") - 3; }
GREET
if cc -O1 -o "$work/greet" "$work/greet.c" 2>/dev/null; then
    info=$("$astral" info "$work/greet")
    check "import: named"          "puts"             "$info"
    check "import: labelled"       "(import) puts"    "$info"
    check "import: second one"     "strlen"           "$info"

    listing=$("$astral" decompile --pseudo-c -f main "$work/greet")
    check "string: printed as a literal" '"Hello, World!"' "$listing"
    check "import: called by name"       "puts("             "$listing"

    unit=$("$astral" decompile --all "$work/greet")
    check "header: emitted for puts"    "#include <stdio.h>" "$unit"
    # The stub belongs to another image, so no body may be emitted for it.
    if printf '%s' "$unit" | grep -qE '^[A-Za-z_0-9 *]+ puts\(.*\)$'; then
        printf 'FAIL import: stub body left out of the unit\n'
        failed=$((failed + 1))
    else
        printf 'ok   import: stub body left out of the unit\n'
        passed=$((passed + 1))
    fi

    # The strongest check available: rebuild the program from its own
    # decompilation and confirm it still prints what it printed before.
    "$astral" decompile --all "$work/greet" > "$work/greet_out.c" 2>/dev/null
    if cc -std=c11 "$work/greet_out.c" -o "$work/greet_rebuilt" 2>"$work/greet.log" \
        && [[ "$("$work/greet_rebuilt")" == "Hello, World!" ]]; then
        printf 'ok   c: rebuilt program reproduces its output\n'
        passed=$((passed + 1))
    else
        printf 'FAIL c: rebuilt program reproduces its output\n%s\n' \
            "$(head -10 "$work/greet.log")"
        failed=$((failed + 1))
    fi
else
    echo "skip import tests: no host compiler"
fi

# --------------------------------------------------------------- real C output
#
# The claim these make is stronger than "it looks like C": the emitted unit is
# handed to a compiler, and for the self-contained functions it is linked and
# run against the behaviour of the original source.

check "c: emits a translation unit" "Decompiled by Astral" \
    "$("$astral" decompile -f add_values "$elf")"

"$astral" decompile -f add_values "$elf" > "$work/add.c" 2>/dev/null
if cc -std=c11 -c "$work/add.c" -o "$work/add.o" 2>"$work/add.log"; then
    printf 'ok   c: elf output compiles\n'
    passed=$((passed + 1))
else
    printf 'FAIL c: elf output compiles\n%s\n' "$(head -10 "$work/add.log")"
    failed=$((failed + 1))
fi

"$astral" decompile -f add_values "$pe" > "$work/add_pe.c" 2>/dev/null
if cc -std=c11 -c "$work/add_pe.c" -o "$work/add_pe.o" 2>"$work/add_pe.log"; then
    printf 'ok   c: pe output compiles\n'
    passed=$((passed + 1))
else
    printf 'FAIL c: pe output compiles\n%s\n' "$(head -10 "$work/add_pe.log")"
    failed=$((failed + 1))
fi

if [[ -x "$work/host" ]]; then
    "$astral" decompile --all "$work/host" > "$work/host_all.c" 2>/dev/null
    if cc -std=c2x -Wall -c "$work/host_all.c" -o "$work/host_all.o" 2>"$work/host.log"; then
        printf 'ok   c: whole macho binary compiles\n'
        passed=$((passed + 1))
    else
        printf 'FAIL c: whole macho binary compiles\n%s\n' "$(head -14 "$work/host.log")"
        failed=$((failed + 1))
    fi

    # Behaviour: link the decompiled functions and compare against the original.
    "$astral" decompile -f add_values -f sum_array "$work/host" > "$work/pure.c" 2>/dev/null
    cat > "$work/drive.c" <<'DRIVER'
#include <stdio.h>
#include <stdint.h>
int32_t add_values(int32_t, int32_t);
int32_t sum_array(int32_t *, uint32_t);
int main(void)
{
    int bad = 0;
    for (int a = -300; a <= 300; a += 13)
        for (int b = -300; b <= 300; b += 17) {
            int s = a + b, want = s > 100 ? s - 100 : s;
            if (add_values(a, b) != want)
                ++bad;
        }
    int32_t v[6] = {1, -2, 3, -4, 5, 100};
    if (sum_array(v, 6) != 103)
        ++bad;
    if (sum_array(v, 0) != 0)
        ++bad;
    return bad != 0;
}
DRIVER
    if cc -std=c11 "$work/pure.c" "$work/drive.c" -o "$work/behave" 2>"$work/behave.log" \
        && "$work/behave"; then
        printf 'ok   c: decompiled functions behave like the original\n'
        passed=$((passed + 1))
    else
        printf 'FAIL c: decompiled functions behave like the original\n%s\n' \
            "$(head -10 "$work/behave.log")"
        failed=$((failed + 1))
    fi
fi

check "c: runtime include mode" "#include <astral/decompiled.h>" \
    "$("$astral" decompile --runtime-include -f add_values "$elf")"

# ------------------------------------------------- naming from evidence
#
# A stripped binary carries no names, but it still prints text, calls library
# functions and uses each value in a shape. These check that Astral reads that
# evidence, and that a name the user chooses outlives the program it was
# chosen in.

cat > "$work/eviden.c" <<'EVIDEN'
#include <stdio.h>
#include <string.h>
int check(const char *given) {
    if (strcmp(given, "hunter2") != 0) { puts("password incorrect"); return 0; }
    return 1;
}
int total_of(const int *v, int n) { int t = 0; for (int i = 0; i < n; ++i) t += v[i]; return t; }
int main(int argc, char **argv) {
    int v[3] = {1, 2, 3};
    if (argc < 2) return 1;
    return check(argv[1]) ? total_of(v, 3) : 0;
}
EVIDEN
if cc -O1 -o "$work/eviden" "$work/eviden.c" 2>/dev/null; then
    check_addr=$("$astral" info "$work/eviden" | awk '/ check$/ {print $1}')
    total_addr=$("$astral" info "$work/eviden" | awk '/ total_of$/ {print $1}')
    cp "$work/eviden" "$work/eviden_stripped"
    strip "$work/eviden_stripped" 2>/dev/null

    named=$("$astral" decompile --why -a "$check_addr" "$work/eviden_stripped" 2>/dev/null)
    check "naming: from a literal"   "verifyPassword"  "$named"
    check "naming: explains itself"  'mentions "password"' "$named"

    summed=$("$astral" decompile -a "$total_addr" "$work/eviden_stripped" 2>/dev/null)
    check "naming: accumulator"      "sum"             "$summed"

    plain=$("$astral" decompile --raw-names -a "$check_addr" "$work/eviden_stripped" 2>/dev/null)
    check "naming: can be turned off" "func_0x"        "$plain"

    check "knowledge: reports its database" "records" "$("$astral" knowledge)"

    # Teaching from a binary that has symbols should let the same bodies be
    # recognised once the symbols are gone. The database used here is a
    # throwaway, so a real one is never touched by the tests.
    export HOME="$work/home"
    mkdir -p "$HOME"
    taught=$("$astral" learn "$work/eviden" 2>&1)
    check "learn: reports what it took in" "learned" "$taught"
    recovered=$("$astral" decompile -a "$check_addr" "$work/eviden_stripped" 2>/dev/null)
    check "learn: name survives stripping" "check" "$recovered"
    unset HOME
    export HOME=$(cd ~ && pwd)
else
    echo "skip naming tests: no host compiler"
fi

# ------------------------------------------------------------------ languages
check "languages listed" "x86:LE:64:default" "$("$astral" languages)"

# --------------------------------------------------------------------- errors
check "missing file reported" "cannot open" \
    "$("$astral" info "$work/does-not-exist" 2>&1 || true)"
check "bad language reported" "unknown language id" \
    "$("$astral" info --language "nope:LE:64:default" "$elf" 2>&1 || true)"

printf '\n%d passed, %d failed\n' "$passed" "$failed"
[[ $failed -eq 0 ]]
